# The purpose of this configuration file is to provide configuration for workflows in the .github/ directory in easy way
# Change setting in this file to enable/disable specific jobs in workflows.

# This setting enables the release workflow
# 'disabled' or 'enabled' values allowed
release: enabled

# Semver minor version
minor_v: 2

# Semver major version
major_v: 0
