name: .Net Unit Tests
run-name: .Net Unit Tests on ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Release a new version"]
    types:
      - completed
  workflow_dispatch:

env:
  PROJECT_NAME: OmniGraphInterview

jobs:
  validate_commit:
    name: Validate Code and Publish Coverage
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Import Secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: https://vault.gcpp.omnigraph.io/
          role: github
          method: jwt
          secrets: |
            /secret/data/databases/astra/integration-testing/role-credentials/readwrite bundle_base64 | ASTRA_BUNDLE ;
            /secret/data/databases/astra/integration-testing/role-credentials/readwrite client_id | ASTRA_CLIENT_ID ;
            /secret/data/databases/astra/integration-testing/role-credentials/readwrite secret | ASTRA_CLIENT_SECRET ;
      - name: Test
        working-directory: ./dotnet/test
        env:
          ASTRA_BUNDLE: ${{ env.ASTRA_BUNDLE }}
          ASTRA_CLIENT_ID: ${{ env.ASTRA_CLIENT_ID }}
          ASTRA_CLIENT_SECRET: ${{ env.ASTRA_CLIENT_SECRET }}
        run: |
          dotnet add package coverlet.msbuild &&
          dotnet test ${PROJECT_NAME}.Tests.csproj --configuration Debug --runtime linux-x64 /p:CollectCoverage=true /p:CoverletOutput=Coverage/ /p:CoverletOutputFormat=lcov --logger GitHubActions
      - name: Publish Code Coverage
        if: ${{ github.event_name == 'pull_request' && always() }}
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./dotnet/test/Coverage/coverage.info
