name: Create Release
run-name: Create Release

on:
  push:
    branches:
      - main

jobs:
  setup_variables:
    name: Load Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@v4.45.1
        id: release
        with:
          cmd: yq '.release' ".github/workflow-configuration.yaml"
      - uses: mikefarah/yq@v4.45.1
        id: major_v
        with:
          cmd: yq '.major_v' ".github/workflow-configuration.yaml"
      - uses: mikefarah/yq@v4.45.1
        id: minor_v
        with:
          cmd: yq '.minor_v' ".github/workflow-configuration.yaml"
    outputs:
      release: ${{ steps.release.outputs.result }}
      major_v: ${{ steps.major_v.outputs.result }}
      minor_v: ${{ steps.minor_v.outputs.result }}

  create_release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [ setup_variables ]
    if: ${{ github.ref == 'refs/heads/main' && always() && needs.setup_variables.outputs.release == 'enabled' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: SneaksAndData/github-actions/semver_release@v0.1.9
        with:
          major_v: ${{needs.setup_variables.outputs.major_v}}
          minor_v: ${{needs.setup_variables.outputs.minor_v}}
